### PR TITLE
Bug fix about a problem with the configuration file

### PR DESCRIPTION
**Pull request by krisdehaudt**
This is a fix for a problem with the configuration file. When autolint
is started for the first time, it will generate a file named
autolint.js. But when for the second time the autolint command is
called, it will try to execute the javascript-file instead of the
command. This is fixed by changing the name of the configuration file so
it doesn't match anymore with the name of the command. Here is the
configuration file called autolintconfig.js.

### CODE REVIEW

**Comment by magnars** [comment]
This is a breaking change, which I would like to avoid. Maybe support two names for the configuration file would be better?

Is it Windows that will execute random javascript-files willy-nilly?

**Comment by krisdehaudt** [comment]
Yes, this is tested on Windows. I don't know if this is also a problem for Linux, because I didn't test it. I find it not such a breaking change because the only change that is made is the name of the configuration file that will be generated. Support of multiple names is also an option if you can configure it with an option at command line. But I think this is more work than just changing the name of the configuration file (it are just 4 changes in the file: configuration.js). 

Another problem i found while working in Windows is that Windows not support the SIGINT signal that is used in on-interrupt.js. In Windows this must be changed in 'exit'. But this is a specific problem for Windows.

**Comment by magnars** [comment]
It is a breaking change, because everyone who upgrades must update every one of their autolint configuration files.

And no, this is not a problem on Linux, because it doesn't run a plain .js-file just because it's there.

There's no problem just checking for the existence of both autolint.js and autolint-config.js when loading it, which would be an acceptable solution.

I'd be happy to accept a separate pull request for the 'exit' signal on Windows, by the way.

**Comment by krisdehaudt** [comment]
Ok, I understand now why this is such a breaking change.

I will make a separate pull request for the 'exit' signal without the other bug fix.

**Pull request closed without merging**
