### PR TITLE
"Suppress messages" feature for JSLint (related to issue #9)

### PR DESCRIPTION
**Pull request by penartur**
Allows to write code like this:

``` javascript
module.exports = {
    linter: 'jslint',
    linterOptions: {
        suppress: { unnecessary_use: true }
    }
}
```

or

``` javascript
"use strict";

var itWillBeStringifiedAndSentToBrowser = function () {
    /*suppress unnecessary_use: true */
    "use strict"; //so that the function will be executed in strict environment in browser
}
```
- Implemented `suppress` setting in `linterOptions`, in the fashion similar to `predef` setting (e.g. `suppress: ['some_message', 'some_other_message']` or `suppress: { some_message: true, some_other_message: true }`). `true` means that the message should be suppressed, false is the default.
- Implemented setting `suppress` setting inline, in the fashion similar to `/*jslint ... */` and `/*global ... */` (e.g. `/*suppress some_message, some_other_message */` or `/*suppress some_message: true, other_message_suppressed_in_an_external_scope: false */`).
- Changed JSLint processing source code files to respect `suppress` setting; if the error JSLint is about to report is suppressed, it won't report about the error nor include it in its report.
- In order to make this with as less pain as possible, some additional modifications were performed. Namely, previously `warn` always returned some return value. `warn` is used everywhere, but we only cared about the return value in `stop`. Now, only `do_warn` returns a return value, and `do_warn` is only called from `warn` and `stop`. In case error passed to `do_warn` should be suppressed, `do_warn` returns false instead of the detailed error info object.

### CODE REVIEW

**Comment by magnars** [comment]
I'm sorry, but changing vendor/jslint.js directly isn't an option. That would mean freezing autolint's jslint-support at todays version. The reason jslint.js is embedded in vendor/ is that Crockford doesn't want to add a module.exports to the official jslint file. I'm still manually updating it from the official repo.

How about the global suppress option I mentioned in the other thread?

**Comment by penartur** [comment]
Now I see your point; I didn't realize at first that it is possible to only change autolint itself, without dealing with the `vendor` code.
I didn't expected you to merge it anyway, it is just for people who may also find it useful and apply the diff to their local version :)

**Comment by magnars** [comment]
The official jslint repo is here: https://github.com/douglascrockford/JSLint if you want to give it a go. :-)

**Comment by penartur** [comment]
Thank you!
Oh, it seems that i'm out of luck: there were many releases since version `autolint` uses, so i have to merge it by hands...

**Comment by penartur** [comment]
By the way, for those who will use `autolint` with the `JSLint` edition from May, there is the actual patch: https://github.com/douglascrockford/JSLint/pull/131

**Pull request closed without merging**
